" https://www.freecodecamp.org/news/vimrc-configuration-guide-customize-your-vim-editor/
source ~/.vim/rc/base-set.vim
source ~/.vim/rc/plugins-load.vim
source ~/.vim/rc/plugins-config.vim
source ~/.vim/rc/base-config.vim
