#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    filetree_direction = "left"
    # using vim compatible mapping for s , ...  
    # enable_language_specific_leader = false
    bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after'

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
  name = "lang#c"
  clang_executable = "/usr/bin/clang"
  enable_clang_syntax_highlight = true
  clang_flag = ['-I/usr/include']
  [layer.clang_std]
    c = "c11"
    cpp = "c++1z"
    objc = "c11"
    objcpp = "c++1z"

[[layers]]
  name = "debug"
  debugger_plugin = "vimspector"

[[layers]]
    name = 'lang#markdown'
    merged=false
    enableWcwidth = 1
    listItemIndent = 1
    enabled_formater = ['prettier']


#[[custom_plugins]]
#  name="preservim/vim-markdown"
#
#[[custom_plugins]]
#  name="iamcco/markdown-preview.nvim"

  #" https://github.com/preservim/vim-markdown
  #Plug 'preservim/vim-markdown'
  #"
  #" https://github.com/iamcco/markdown-preview.nvim  
  #"Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app && yarn install'  }


